//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalDataCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalDataCollector.Resources.GeneralConfiguration", typeof(GeneralConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the IP adress of your PC.
        ///An IP address is a way of identifying your computer uniquely on a network (and on the Internet).
        ///
        ///In Windows10, to find out what your IP is, go to:
        ///Windows Settings -&gt; Network &amp; Internet -&gt; Properties of your connection
        ///The IPv4 field should give an identifier of the form 172.16.254.1.
        /// </summary>
        public static string HomeIPHelp {
            get {
                return ResourceManager.GetString("HomeIPHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the IP adress of your Raspberry Pi.
        ///An IP address is a way of identifying your Raspberry Pi uniquely on a network (and on the Internet).
        ///
        ///In Linux, to find out what your IP is, on the command line of the shell type:
        ///hostname -I
        ///
        ///You should get an identifier of the form 172.16.254.1.
        /// </summary>
        public static string RaspberryIPHelp {
            get {
                return ResourceManager.GetString("RaspberryIPHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Raspberry password..
        /// </summary>
        public static string RaspberryPasswordHelp {
            get {
                return ResourceManager.GetString("RaspberryPasswordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Raspberry port..
        /// </summary>
        public static string RaspberryPortHelp {
            get {
                return ResourceManager.GetString("RaspberryPortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Raspberry user..
        /// </summary>
        public static string RaspberryUserHelp {
            get {
                return ResourceManager.GetString("RaspberryUserHelp", resourceCulture);
            }
        }
    }
}
